INSERT_INTO = "INSERT INTO {tableName} VALUES ({values});"
GET_MAX = "SELECT MAX({key}) FROM {tableName};"
SIMPLE_SELECT = "SELECT {columns} FROM {tableName} WHERE {conditions};"
UPDATE = "UPDATE {tableName} SET {values} WHERE {conditions}"
GET_ALL_POTS = "SELECT * FROM {tableName} WHERE owner='{owner}' OR id IN ({idList});"